name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Go ----
      - name: Set up Go
        if: ${{ hashFiles('**/*.go') != '' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Go env
        if: ${{ hashFiles('**/*.go') != '' }}
        run: |
          go version
          go env GOVERSION GOMOD

      - name: Go build (cmd/* -> bin/)
        if: ${{ hashFiles('**/*.go') != '' }}
        run: |
          set -e
          mkdir -p bin
          if [ -d "cmd" ]; then
            for d in cmd/*; do
              [ -d "$d" ] || continue
              if grep -q "package main" "$d"/*.go 2>/dev/null; then
                name="$(basename "$d")"
                echo "[go build] $d -> bin/$name"
                go build -o "bin/$name" "./$d"
              fi
            done
          fi

      # ---- Rust ----
      - name: Set up Rust
        if: ${{ hashFiles('core/**/Cargo.toml') != '' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cargo fmt & check & test
        if: ${{ hashFiles('core/**/Cargo.toml') != '' }}
        working-directory: core
        run: |
          cargo fmt --all -- --check || true
          cargo check
          cargo test -q
