name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Go (only if there is any .go file) ----
      - name: Set up Go
        if: ${{ hashFiles('**/*.go') != '' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
          check-latest: true

      - name: Go env
        if: ${{ hashFiles('**/*.go') != '' }}
        run: |
          go version
          go env GOVERSION GOMOD

      - name: Go fmt & vet
        if: ${{ hashFiles('**/*.go') != '' }}
        run: |
          go fmt ./...
          go vet ./...

      - name: Go build
        if: ${{ hashFiles('**/*.go') != '' }}
        run: go build ./...

      # ---- Rust (only if there is a Cargo.toml under core/) ----
      - name: Set up Rust
        if: ${{ hashFiles('core/**/Cargo.toml') != '' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cargo fmt & check & test
        if: ${{ hashFiles('core/**/Cargo.toml') != '' }}
        run: |
          cargo fmt --all -- --check || true
          cargo check
          cargo test -q
