name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Go ----
      - name: Set up Go
        if: ${{ hashFiles('**/*.go') != '' }}
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Go fmt & vet
        if: ${{ hashFiles('**/*.go') != '' }}
        run: |
          go fmt ./...
          go vet ./...

      - name: Go build
        if: ${{ hashFiles('**/*.go') != '' }}
        run: go build ./...

      # ---- Rust ----
      - name: Set up Rust
        if: ${{ hashFiles('core/**/Cargo.toml') != '' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cargo fmt & check
        if: ${{ hashFiles('core/**/Cargo.toml') != '' }}
        run: |
          cargo fmt --all -- --check || true
          cargo check

      # ---- Markdown links (soft-fail) ----
      - name: Markdown link check (README)
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        continue-on-error: true
        with:
          use-quiet-mode: 'yes'
          config-file: '.mlc-config.json'
          file-path: 'README.md'
